### ISSUE TITLE
novezeny.eu - webarchiv verze

### ISSUE THREAD

**Issue by ghost** [WebArchivCZ/OpenWayback-devel#11]
Stránka novezeny.eu vede v několik archivních verzích na starší webarchiv.cz

- únor 2010
- březen 2010

http://wayback.webarchiv.cz/secure/20100224144650/http://www.novezeny.eu/

šlo by to vymazat/vyrušit nebo tak něco?

**Comment by kvasnicaj** [comment]
bohužel nevyřešíme, byl to bug u starších sklizní
