### ISSUE TITLE
techcorp.cz - wayback 

### ISSUE THREAD

**Issue by ghost** [WebArchivCZ/OpenWayback-devel#12]
Ve waybacku mi stránka techcorp.cz (TC encyklopedie) hlásí, že nelze zobrazit, pouze z Klementina

http://wayback.webarchiv.cz/secure/*/http://www.techcorp.cz

Dalo by se s tím něco dělat? Máme na ni smlouvu, web aktuálně neběží.

@westfood

**Comment by JanMeritus** [comment]
Nie je v seminkach (gen 1r)

**Comment by kvasnicaj** [comment]
přidáno do whitelistu, ale nezobrazuje se ani na secure. Jinak je to mrtvý web.

**Comment by kvasnicaj** [comment]
aha, tak je to blacklisted semínko
