### ISSUE TITLE
safebryo.cz - virus

### ISSUE THREAD

**Issue by ghost** [WebArchivCZ/OpenWayback-devel#13]
Zdravím,
stránky safebryo.cz hází v některých archivních verzích hlášku, že máme vira a že to teda není dobrý...

http://wayback.webarchiv.cz/secure/20091107220913/http://www.safebryo.cz/

![image](https://cloud.githubusercontent.com/assets/22216442/25526020/fd9ae682-2c11-11e7-99ea-aa695c9a0b71.png)

**Comment by kvasnicaj** [comment]
#14

**Comment by kvasnicaj** [comment]
mrtvý web
