### ISSUE TITLE
safebryo - font

### ISSUE THREAD

**Issue by ghost** [WebArchivCZ/OpenWayback-devel#14]
Zdravím, 
safebryo.cz - má nějaké rozházené fonty - nemám tušení čím to je - ale třeba do budoucna by bylo fajn vědět, proč a aby se to už nestávalo, pokud původní web je v pohodě...

http://wayback.webarchiv.cz/secure/20071003065857/http://safebryo.cz/farmakoepidemiologie.htm

![image](https://cloud.githubusercontent.com/assets/22216442/25526345/71532e6c-2c13-11e7-97b0-ee42c9aa7d4e.png)

**Comment by ghost** [comment]
Přidávám další web, který je rozhašený - resp spíš jenom podstránky: http://wayback.webarchiv.cz/secure/20060910162049/http://www.nekurte.cz/clanky/teories.htm
a http://wayback.webarchiv.cz/secure/20060801204138/http://www.nekurte.cz/nadory.html

**Comment by kvasnicaj** [comment]
u toho nekurte je to špatně nastavené kodování u zdroje, s tím už asi nic neuděláme.

**Comment by kvasnicaj** [comment]
jinak zavírám, safebryo už jedno issue má
