### ISSUE TITLE
obalkyknih.cz - poškozená archivní verze z roku 2017

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/OpenWayback-devel#17]
u zdroje http://www.obalkyknih.cz je poškozená archivní verze z roku 2017 (tím pádem na ní odkazuje  adresa z katalogizačního záznamu v databázi NK http://wayback.webarchiv.cz/wayback/http://www.obalkyknih.cz )

![obalky knih](https://cloud.githubusercontent.com/assets/19947819/25747533/13b8ed1a-31a8-11e7-947c-e3d6bfd6db26.png)

**Comment by kvasnicaj** [comment]
@mariehaskovcova jak to vypadá s nejnovějšími archivními kopiemi?

**Comment by mariehaskovcova** [comment]
kopie 2018 vypadají ok, teda zrovna u té poslední zaindexované verze jsou rozsypané styly, ale obsah tam je https://wayback.webarchiv.cz/wayback/20180613191655/http://www.obalkyknih.cz/
