### ISSUE TITLE
aleph.nkp.cz/web/ok.htm - Ohlášené knihy - minimální obsah

### ISSUE THREAD

**Issue by ghost** [WebArchivCZ/OpenWayback-devel#18]
Ahoj,
archivní verze webu ohlášených knih (NKP) jsou velmi strohé - obsahují v podstatě jen první informační stránku a jinak je tam prázdno. Dalo by se s tím něco dělat? 

viz http://wayback.webarchiv.cz/secure/20160324123338/http://aleph.nkp.cz/web/ok.htm 

Děkuju

**Comment by kvasnicaj** [comment]
nepodařilo sklidit, technické ne
