### ISSUE TITLE
BubbleCalendar's logo

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/OpenWayback-devel#2]
BubbleCalendar's logo should go to http://wayback.webarchiv.cz:8080/wayback/ without using absolute link.

**Comment by jstavel** [comment]
Do you mean: <img src="http://wayback.webarchiv.cz:8080/wayback/images/OpenWayback-banner.png ?

**Comment by westfood** [comment]
We use this repository for other purposes too. 

Check this commit: https://github.com/WebArchivCZ/OpenWayback-devel/commit/69d7af4ebf9492ac0b5e9ea5f141930c308f3d77 -- There is a problem that BubbleCalendar creates bad URL when we use relative path, we do not want us absolute URL, because there is different one for curator00.webarchiv.cz and wayback.webarchiv.cz. So for now clicking on logo here will bring you nowhere: http://wayback.webarchiv.cz:8080/wayback/*/http://galeriezlin.cz :-)

**Comment by kvasnicaj** [comment]
Hyperlink on toolbar's logo which is working correctly looks like this: 

```
<a href="<%= staticPrefix %>"><img ...></a>
```

or maybe will works someting like this:

```
<a href="<%= staticPrefix %>/index.jsp"><img ...></a>
```

I think it's worth a shot. :+1:
