### ISSUE TITLE
whitelist - dostupnost zdroje zvenčí

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/OpenWayback-devel#21]
semínko www.pazourek.kamen.kamenu.sweb.cz je na whitelistu, mělo by být veřejné, přesto zvenčí není vidět - odkazuje do referenčního centra

**Comment by JanMeritus** [comment]
Kedy ste ho pridali? Done :)

**Comment by mariehaskovcova** [comment]
@JanMeritus Zdroj jsme přidali v květnu 2017. Díky
