### ISSUE TITLE
arnika.org/ekoporadna - nezobrazí se hlavička archivní kopie

### ISSUE THREAD

**Issue by Bilinova** [WebArchivCZ/OpenWayback-devel#26]
U zdroje http://arnika.org/ekoporadna se ve waybacku nezobrazí hlavička 
![image](https://user-images.githubusercontent.com/13220888/44020758-314a9974-9ee3-11e8-8068-508317ed9c9f.png) při prohlížení archivní verze viz 
![image](https://user-images.githubusercontent.com/13220888/44020811-622450a8-9ee3-11e8-8e6e-e4314eeca0e9.png) . Archivní verze ae jinak zobrazuje v pořádku.

**Comment by kvasnicaj** [comment]
s tím bohužel asi nic neuděláme, ale aspoň archivní verze fungují
