### ISSUE TITLE
http://jlk.upol.cz/ - Jazyk - Literatura -Komunikace

### ISSUE THREAD

**Issue by Hartmanova** [WebArchivCZ/OpenWayback-devel#29]
Poslední viditelná harvestace 2015, ale univerzitní časopisel vyšel i v roce 2016, 2017.  Proč již není sbírán? Lze ho opět zařadit do výběrové sklizně?

**Comment by mariehaskovcova** [comment]
v archivu máme původní adresu, na které časopis vycházel (http://www.jazyk-literatura-komunikace.cz), aktuální adresu časopisu (http://jlk.upol.cz) teď zařadíme do nejbližší výběrové sklizně

**Comment by kvasnicaj** [comment]
od roku 2018 už byla zařazena nová adresa a jsou dostupné první archivní verze
