### ISSUE TITLE
https://svkhk.cz/Pro-knihovny/Zpravodaj-U-nas/Aktualni-cislo.aspx - U nás

### ISSUE THREAD

**Issue by Hartmanova** [WebArchivCZ/OpenWayback-devel#30]
Poslední viditelný sběr květen 2018, ale dá se dostat pouze k webarchiv verzi posledního čísla roku 2017. Doposud vyšly už 3 čísla roku 2018 a není viditelná žádná archivní verze. Objeví se do konce roku nějaká archivní verze časopisu z roku 2018? Děkuji

**Comment by mariehaskovcova** [comment]
dobrý den, nastavíme častější frekvenci pro sklízení zpravodaje, sklidit by se měla všechna jeho čísla v sekci Archiv čísel (od roku 1999). Sklizená data budou viditelná až po indexaci, do konce roku by měly být nejnovější archivní kopie již dostupné

**Comment by kvasnicaj** [comment]
v nových sklizní jsou nové archivní verze a jsou nyní už dostupné
