### ISSUE TITLE
https://wayback.webarchiv.cz/wayback/*/http://www.phil.muni.cz/journals/proudy/

### ISSUE THREAD

**Issue by Hartmanova** [WebArchivCZ/OpenWayback-devel#31]
Archiv časopisu Proudy byl dostupný mimo Referenční centrum. Nyní je dostupná jen jeho verze z r. 2011 a ostatní již ne. Je toto už trvalý stav kvůli změně smlouvy? Nebo se jedná o nějaký omyl. Děkuji za vysvětlení. Pavla Hartmanová (ÚČL)

**Comment by mariehaskovcova** [comment]
dobrý den, smlouva je v pořádku, jde o technický problém, který může souviset s indexací dat. Děkujeme za upozornění, zdroj prověříme.

**Comment by mariehaskovcova** [comment]
dobrý den, problém se zobrazením způsobilo přesměrování původní url adresy http://www.phil.muni.cz/journals/proudy/ na adresu http://www.phil.muni.cz/journal/proudy/  (journals x journal). Zadali jsme nové semínko do whitelistu, při jeho nejbližší aktualizaci by již kopie měly být dostupné mimo Referenční centrum

**Comment by Hartmanova** [comment]
Dobrý den,
moc děkuji. Pavla Hartmanová

**Comment by kvasnicaj** [comment]
vyřešeno, otestováno a funguje
