### ISSUE TITLE
špatná archivní verze stránek - ŘSD

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/OpenWayback-devel#7]
při katalogizaci zdroje  http://www.rsd.cz  v Alephu se uložila archivní verze stránek takto:
http://wayback.webarchiv.cz/wayback/http://www.rsd.cz (archivní verze stránek)

**Comment by kvasnicaj** [comment]
Chyba je v přesměrování. Prosím uprav v katalogu archivní URL na https://www.rsd.cz/wps/portal/

tj. http://wayback.webarchiv.cz/wayback/http://www.rsd.cz/wps/portal/

Až upravíš, tak to issue prosím uzavři. 

Dále prosím, aby všechny nové issue byly oznámeny na následující poradě. Díky, ať to tu neleží měsíc :) @mariehaskovcova

**Comment by mariehaskovcova** [comment]
díky, opraveno, uzavírám

**Comment by mariehaskovcova** [comment]
díky, opraveno, uzavírám

@kvasnicaj 
@mariehaskovcova
